### ISSUE TITLE
No flag to specify VPP default gateway

### ISSUE THREAD

**Issue by laaubert** [calico-vpp/calico-vpp#8]
Today, VPP will automatically detects and copies the routes of the linux interface assigned to VPP.

If there is no default route attached to that interface (could be used with another interface already), VPP won't have any default gw which could be a challenge to send traffic to the outside when BGP is not an option.

We need a flag in the configmap so we can specify this default gw.

Thanks,
Laurent.

**Comment by AloysAugustin** [comment]
Hi @laaubert , I see two options to solve this, one is as you mention pass a default GW to VPP through an environment variable, and the other would be to configure the other routes that exist on the host (including the default route in your case) in VPP, directing the traffic to the host through `vpptap0`. 

So the question is, in your use case, do you need to specify a default GW for VPP that is different from the host's default GW?

**Comment by laaubert** [comment]
Hi Aloÿs,

 

In my case, VPP default GW is different from the one used by the Host.

 

Thanks,

Laurent.
